export const characters = [
    {
        id: 'Totoro',
        title: 'Тоторо',
        image: '/src/img/characters/totoro.jpg',
        body: 'Тоторо - хранитель леса, большое мохнатое существо серого цвета, которое полностью придумал Миядзаки. Не умеет говорить, только рычать. Дружелюбен к главным героиням.',
        readMore: true,
    },
    {
        id: 'Satsuki',
        title: 'Сацуки Кусакабэ',
        image: '/src/img/characters/satsuki.jpg',
        body: 'Старшая из сестер, ответственная и бойкая девочка десяти лет. Выполняет или помогает выполнять многие обязанности по дому. Заботится о Мэй. ',
        readMore: false,
    },
    {
        id: 'Mei',
        title: 'Мэй Кусакабэ',
        image: '/src/img/characters/mei.jpg',
        body: 'Младшая в семье, 4 года. Любознательна, непоседлива и упряма. Во многом старается быть похожей на старшую сестру. ',
        readMore: false,
    },
    {
        id: 'Tatsuo',
        title: 'Тацуо Кусакабэ',
        image: '/src/img/characters/Tatsuo.jpg',
        body: '',
        readMore: false,
    },
    {
        id: 'Yasuko',
        title: 'Ясуко Кусакабэ',
        image: '/src/img/characters/Yasuko.jpg',
        body: '',
        readMore: false,
    },
    {
        id: 'Granny',
        title: 'Бабушка',
        image: '/src/img/characters/granny.jpg',
        body: '',
        readMore: false,
    },
    {
        id: 'Kanta',
        title: 'Канта Огаки',
        image: '/src/img/characters/Kanta.jpg',
        body: '',
        readMore: false,
    },
    {
        id: 'Catbus',
        title: 'Котобус',
        image: '/src/img/characters/сatbus.jpg',
        body: '',
        readMore: false,
    },
    {
        id: 'Chu',
        title: 'Чу Тоторо',
        image: '/src/img/characters/Chu.jpg',
        body: '',
        readMore: false,
    },
    {
        id: 'Chibi',
        title: 'Чиби Тоторо',
        image: '/src/img/characters/Chibi.jpg',
        body: '',
        readMore: false,
    },
    {
        id: 'Susuwatari',
        title: 'Чернушки',
        image: '/src/img/characters/Susuwatari.jpg',
        body: '',
        readMore: false,
    },
];